version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "14:15"
      timezone: "America/New_York"
    reviewers:
      - "cmu-sei/crucible-team-developers"
